// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice = HeroSlice;

interface PageDocumentData {
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<PageDocumentData, "page", Lang>;

export type AllDocumentTypes = PageDocument;

export interface HeroSliceDefaultPrimary {
  title: prismic.RichTextField;
  description: prismic.RichTextField;
}

export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

type HeroSliceVariation = HeroSliceDefault;

export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefault,
      HeroSliceVariation,
    };
  }
}
